server:
  port: ${PORT}

company:
  product:
    id: ${PRODUCT_ID}
  orgws:
    token:
      url: ${ORGWS_TOKEN_URL}

firestore:
  database:
    url: ${DB_URL}
    credentials: ${DB_SECRET}

youtube:
  api:
    key: ${YOUTUBE_API_KEY}

sendinblue:
  api:
    key: ${SENDINBLUE_API_KEY}